<?php

    $dexDB = '{
        "001": [{"name": "bulbasaur", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "002": [{"name": "ivysaur", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "003": [{"name": "venusaur", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "004": [{"name": "charmander", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "005": [{"name": "charmeleon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "006": [{"name": "charizard", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "007": [{"name": "squirtle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "008": [{"name": "wartortle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "009": [{"name": "blastoise", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "010": [{"name": "caterpie", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "011": [{"name": "metapod", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "012": [{"name": "butterfree", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "013": [{"name": "weedle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "014": [{"name": "kakuna", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "015": [{"name": "beedrill", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "016": [{"name": "pidgey", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "017": [{"name": "pidgeotto", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "018": [{"name": "pidgeot", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "019": [{"name": "rattata", "alola": true, "galar": false,
		"hisuian": false,
		"gender": true}],
        "020": [{"name": "raticate", "alola": true, "galar": false,
		"hisuian": false,
		"gender": true}],
        "021": [{"name": "spearow", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "022": [{"name": "fearow", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "023": [{"name": "ekans", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "024": [{"name": "arbok", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "025": [{"name": "pikachu", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "026": [{"name": "raichu", "alola": true, "galar": false,
		"hisuian": false,
		"gender": true}],
        "027": [{"name": "sandshrew", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "028": [{"name": "sandslash", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "029": [{"name": "nidoran-f", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "030": [{"name": "nidorina", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "031": [{"name": "nidoqueen", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "032": [{"name": "nidoran-m", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "033": [{"name": "nidorino", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "034": [{"name": "nidoking", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "035": [{"name": "clefairy", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "036": [{"name": "clefable", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "037": [{"name": "vulpix", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "038": [{"name": "ninetales", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "039": [{"name": "jigglypuff", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "040": [{"name": "wigglytuff", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "041": [{"name": "zubat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "042": [{"name": "golbat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "043": [{"name": "oddish", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "044": [{"name": "gloom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "045": [{"name": "vileplume", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "046": [{"name": "paras", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "047": [{"name": "parasect", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "048": [{"name": "venonat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "049": [{"name": "venomoth", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "050": [{"name": "diglett", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "051": [{"name": "dugtrio", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "052": [{"name": "meowth", "alola": true, "galar": true,
		"hisuian": false,
		"gender": false}],
        "053": [{"name": "persian", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "054": [{"name": "psyduck", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "055": [{"name": "golduck", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "056": [{"name": "mankey", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "057": [{"name": "primeape", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "058": [{"name": "growlithe", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "059": [{"name": "arcanine", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "060": [{"name": "poliwag", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "061": [{"name": "poliwhirl", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "062": [{"name": "poliwrath", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "063": [{"name": "abra", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "064": [{"name": "kadabra", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "065": [{"name": "alakazam", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "066": [{"name": "machop", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "067": [{"name": "machoke", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "068": [{"name": "machamp", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "069": [{"name": "bellsprout", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "070": [{"name": "weepinbell", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "071": [{"name": "victreebel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "072": [{"name": "tentacool", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "073": [{"name": "tentacruel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "074": [{"name": "geodude", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "075": [{"name": "graveler", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "076": [{"name": "golem", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "077": [{"name": "ponyta", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "078": [{"name": "rapidash", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "079": [{"name": "slowpoke", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "080": [{"name": "slowbro", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "081": [{"name": "magnemite", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "082": [{"name": "magneton", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "083": [{"name": "farfetchd", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "084": [{"name": "doduo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "085": [{"name": "dodrio", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "086": [{"name": "seel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "087": [{"name": "dewgong", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "088": [{"name": "grimer", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "089": [{"name": "muk", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "090": [{"name": "shellder", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "091": [{"name": "cloyster", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "092": [{"name": "gastly", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "093": [{"name": "haunter", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "094": [{"name": "gengar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "095": [{"name": "onix", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "096": [{"name": "drowzee", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "097": [{"name": "hypno", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "098": [{"name": "krabby", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "099": [{"name": "kingler", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "100": [{"name": "voltorb", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "101": [{"name": "electrode", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "102": [{"name": "exeggcute", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "103": [{"name": "exeggutor", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "104": [{"name": "cubone", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "105": [{"name": "marowak", "alola": true, "galar": false,
		"hisuian": false,
		"gender": false}],
        "106": [{"name": "hitmonlee", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "107": [{"name": "hitmonchan", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "108": [{"name": "lickitung", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "109": [{"name": "koffing", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "110": [{"name": "weezing", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "111": [{"name": "rhyhorn", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "112": [{"name": "rhydon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "113": [{"name": "chansey", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "114": [{"name": "tangela", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "115": [{"name": "kangaskhan", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "116": [{"name": "horsea", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "117": [{"name": "seadra", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "118": [{"name": "goldeen", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "119": [{"name": "seaking", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "120": [{"name": "staryu", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "121": [{"name": "starmie", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "122": [{"name": "mr-mime", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "123": [{"name": "scyther", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "124": [{"name": "jynx", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "125": [{"name": "electabuzz", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "126": [{"name": "magmar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "127": [{"name": "pinsir", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "128": [{"name": "tauros", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "129": [{"name": "magikarp", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "130": [{"name": "gyarados", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "131": [{"name": "lapras", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "132": [{"name": "ditto", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "133": [{"name": "eevee", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "134": [{"name": "vaporeon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "135": [{"name": "jolteon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "136": [{"name": "flareon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "137": [{"name": "porygon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "138": [{"name": "omanyte", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "139": [{"name": "omastar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "140": [{"name": "kabuto", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "141": [{"name": "kabutops", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "142": [{"name": "aerodactyl", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "143": [{"name": "snorlax", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "144": [{"name": "articuno", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "145": [{"name": "zapdos", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "146": [{"name": "moltres", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "147": [{"name": "dratini", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "148": [{"name": "dragonair", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "149": [{"name": "dragonite", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "150": [{"name": "mewtwo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "151": [{"name": "mew", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "152": [{"name": "chikorita", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "153": [{"name": "bayleef", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "154": [{"name": "meganium", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "155": [{"name": "cyndaquil", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "156": [{"name": "quilava", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "157": [{"name": "typhlosion", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "158": [{"name": "totodile", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "159": [{"name": "croconaw", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "160": [{"name": "feraligatr", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "161": [{"name": "sentret", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "162": [{"name": "furret", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "163": [{"name": "hoothoot", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "164": [{"name": "noctowl", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "165": [{"name": "ledyba", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "166": [{"name": "ledian", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "167": [{"name": "spinarak", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "168": [{"name": "ariados", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "169": [{"name": "crobat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "170": [{"name": "chinchou", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "171": [{"name": "lanturn", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "172": [{"name": "pichu", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "173": [{"name": "cleffa", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "174": [{"name": "igglybuff", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "175": [{"name": "togepi", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "176": [{"name": "togetic", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "177": [{"name": "natu", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "178": [{"name": "xatu", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "179": [{"name": "mareep", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "180": [{"name": "flaaffy", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "181": [{"name": "ampharos", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "182": [{"name": "bellossom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "183": [{"name": "marill", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "184": [{"name": "azumarill", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "185": [{"name": "sudowoodo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "186": [{"name": "politoed", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "187": [{"name": "hoppip", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "188": [{"name": "skiploom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "189": [{"name": "jumpluff", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "190": [{"name": "aipom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "191": [{"name": "sunkern", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "192": [{"name": "sunflora", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "193": [{"name": "yanma", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "194": [{"name": "wooper", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "195": [{"name": "quagsire", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "196": [{"name": "espeon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "197": [{"name": "umbreon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "198": [{"name": "murkrow", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "199": [{"name": "slowking", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "200": [{"name": "misdreavus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "201": [{"name": "unown", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "202": [{"name": "wobbuffet", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "203": [{"name": "girafarig", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "204": [{"name": "pineco", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "205": [{"name": "forretress", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "206": [{"name": "dunsparce", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "207": [{"name": "gligar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "208": [{"name": "steelix", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "209": [{"name": "snubbull", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "210": [{"name": "granbull", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "211": [{"name": "qwilfish", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "212": [{"name": "scizor", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "213": [{"name": "shuckle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "214": [{"name": "heracross", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "215": [{"name": "sneasel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "216": [{"name": "teddiursa", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "217": [{"name": "ursaring", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "218": [{"name": "slugma", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "219": [{"name": "magcargo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "220": [{"name": "swinub", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "221": [{"name": "piloswine", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "222": [{"name": "corsola", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "223": [{"name": "remoraid", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "224": [{"name": "octillery", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "225": [{"name": "delibird", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "226": [{"name": "mantine", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "227": [{"name": "skarmory", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "228": [{"name": "houndour", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "229": [{"name": "houndoom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "230": [{"name": "kingdra", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "231": [{"name": "phanpy", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "232": [{"name": "donphan", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "233": [{"name": "porygon2", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "234": [{"name": "stantler", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "235": [{"name": "smeargle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "236": [{"name": "tyrogue", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "237": [{"name": "hitmontop", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "238": [{"name": "smoochum", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "239": [{"name": "elekid", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "240": [{"name": "magby", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "241": [{"name": "miltank", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "242": [{"name": "blissey", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "243": [{"name": "raikou", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "244": [{"name": "entei", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "245": [{"name": "suicune", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "246": [{"name": "larvitar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "247": [{"name": "pupitar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "248": [{"name": "tyranitar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "249": [{"name": "lugia", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "250": [{"name": "ho-oh", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "251": [{"name": "celebi", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "252": [{"name": "treecko", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "253": [{"name": "grovyle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "254": [{"name": "sceptile", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "255": [{"name": "torchic", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "256": [{"name": "combusken", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "257": [{"name": "blaziken", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "258": [{"name": "mudkip", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "259": [{"name": "marshtomp", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "260": [{"name": "swampert", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "261": [{"name": "poochyena", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "262": [{"name": "mightyena", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "263": [{"name": "zigzagoon", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "264": [{"name": "linoone", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "265": [{"name": "wurmple", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "266": [{"name": "silcoon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "267": [{"name": "beautifly", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "268": [{"name": "cascoon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "269": [{"name": "dustox", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "270": [{"name": "lotad", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "271": [{"name": "lombre", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "272": [{"name": "ludicolo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "273": [{"name": "seedot", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "274": [{"name": "nuzleaf", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "275": [{"name": "shiftry", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "276": [{"name": "taillow", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "277": [{"name": "swellow", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "278": [{"name": "wingull", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "279": [{"name": "pelipper", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "280": [{"name": "ralts", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "281": [{"name": "kirlia", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "282": [{"name": "gardevoir", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "283": [{"name": "surskit", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "284": [{"name": "masquerain", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "285": [{"name": "shroomish", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "286": [{"name": "breloom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "287": [{"name": "slakoth", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "288": [{"name": "vigoroth", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "289": [{"name": "slaking", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "290": [{"name": "nincada", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "291": [{"name": "ninjask", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "292": [{"name": "shedinja", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "293": [{"name": "whismur", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "294": [{"name": "loudred", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "295": [{"name": "exploud", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "296": [{"name": "makuhita", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "297": [{"name": "hariyama", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "298": [{"name": "azurill", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "299": [{"name": "nosepass", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "300": [{"name": "skitty", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "301": [{"name": "delcatty", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "302": [{"name": "sableye", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "303": [{"name": "mawile", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "304": [{"name": "aron", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "305": [{"name": "lairon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "306": [{"name": "aggron", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "307": [{"name": "meditite", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "308": [{"name": "medicham", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "309": [{"name": "electrike", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "310": [{"name": "manectric", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "311": [{"name": "plusle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "312": [{"name": "minun", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "313": [{"name": "volbeat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "314": [{"name": "illumise", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "315": [{"name": "roselia", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "316": [{"name": "gulpin", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "317": [{"name": "swalot", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "318": [{"name": "carvanha", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "319": [{"name": "sharpedo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "320": [{"name": "wailmer", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "321": [{"name": "wailord", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "322": [{"name": "numel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "323": [{"name": "camerupt", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "324": [{"name": "torkoal", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "325": [{"name": "spoink", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "326": [{"name": "grumpig", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "327": [{"name": "spinda", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "328": [{"name": "trapinch", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "329": [{"name": "vibrava", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "330": [{"name": "flygon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "331": [{"name": "cacnea", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "332": [{"name": "cacturne", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "333": [{"name": "swablu", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "334": [{"name": "altaria", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "335": [{"name": "zangoose", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "336": [{"name": "seviper", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "337": [{"name": "lunatone", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "338": [{"name": "solrock", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "339": [{"name": "barboach", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "340": [{"name": "whiscash", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "341": [{"name": "corphish", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "342": [{"name": "crawdaunt", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "343": [{"name": "baltoy", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "344": [{"name": "claydol", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "345": [{"name": "lileep", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "346": [{"name": "cradily", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "347": [{"name": "anorith", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "348": [{"name": "armaldo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "349": [{"name": "feebas", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "350": [{"name": "milotic", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "351": [{"name": "castform", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "352": [{"name": "kecleon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "353": [{"name": "shuppet", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "354": [{"name": "banette", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "355": [{"name": "duskull", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "356": [{"name": "dusclops", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "357": [{"name": "tropius", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "358": [{"name": "chimecho", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "359": [{"name": "absol", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "360": [{"name": "wynaut", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "361": [{"name": "snorunt", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "362": [{"name": "glalie", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "363": [{"name": "spheal", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "364": [{"name": "sealeo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "365": [{"name": "walrein", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "366": [{"name": "clamperl", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "367": [{"name": "huntail", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "368": [{"name": "gorebyss", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "369": [{"name": "relicanth", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "370": [{"name": "luvdisc", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "371": [{"name": "bagon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "372": [{"name": "shelgon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "373": [{"name": "salamence", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "374": [{"name": "beldum", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "375": [{"name": "metang", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "376": [{"name": "metagross", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "377": [{"name": "regirock", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "378": [{"name": "regice", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "379": [{"name": "registeel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "380": [{"name": "latias", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "381": [{"name": "latios", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "382": [{"name": "kyogre", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "383": [{"name": "groudon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "384": [{"name": "rayquaza", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "385": [{"name": "jirachi", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "386": [{"name": "deoxys", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "387": [{"name": "turtwig", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "388": [{"name": "grotle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "389": [{"name": "torterra", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "390": [{"name": "chimchar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "391": [{"name": "monferno", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "392": [{"name": "infernape", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "393": [{"name": "piplup", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "394": [{"name": "prinplup", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "395": [{"name": "empoleon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "396": [{"name": "starly", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "397": [{"name": "staravia", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "398": [{"name": "staraptor", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "399": [{"name": "bidoof", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "400": [{"name": "bibarel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "401": [{"name": "kricketot", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "402": [{"name": "kricketune", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "403": [{"name": "shinx", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "404": [{"name": "luxio", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "405": [{"name": "luxray", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "406": [{"name": "budew", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "407": [{"name": "roserade", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "408": [{"name": "cranidos", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "409": [{"name": "rampardos", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "410": [{"name": "shieldon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "411": [{"name": "bastiodon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "412": [{"name": "burmy", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "413": [{"name": "wormadam", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "414": [{"name": "mothim", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "415": [{"name": "combee", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "416": [{"name": "vespiquen", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "417": [{"name": "pachirisu", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "418": [{"name": "buizel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "419": [{"name": "floatzel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "420": [{"name": "cherubi", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "421": [{"name": "cherrim", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "422": [{"name": "shellos", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "423": [{"name": "gastrodon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "424": [{"name": "ambipom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "425": [{"name": "drifloon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "426": [{"name": "drifblim", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "427": [{"name": "buneary", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "428": [{"name": "lopunny", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "429": [{"name": "mismagius", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "430": [{"name": "honchkrow", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "431": [{"name": "glameow", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "432": [{"name": "purugly", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "433": [{"name": "chingling", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "434": [{"name": "stunky", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "435": [{"name": "skuntank", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "436": [{"name": "bronzor", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "437": [{"name": "bronzong", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "438": [{"name": "bonsly", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "439": [{"name": "mime-jr", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "440": [{"name": "happiny", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "441": [{"name": "chatot", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "442": [{"name": "spiritomb", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "443": [{"name": "gible", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "444": [{"name": "gabite", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "445": [{"name": "garchomp", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "446": [{"name": "munchlax", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "447": [{"name": "riolu", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "448": [{"name": "lucario", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "449": [{"name": "hippopotas", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "450": [{"name": "hippowdon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "451": [{"name": "skorupi", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "452": [{"name": "drapion", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "453": [{"name": "croagunk", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "454": [{"name": "toxicroak", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "455": [{"name": "carnivine", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "456": [{"name": "finneon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "457": [{"name": "lumineon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "458": [{"name": "mantyke", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "459": [{"name": "snover", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "460": [{"name": "abomasnow", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "461": [{"name": "weavile", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "462": [{"name": "magnezone", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "463": [{"name": "lickilicky", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "464": [{"name": "rhyperior", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "465": [{"name": "tangrowth", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "466": [{"name": "electivire", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "467": [{"name": "magmortar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "468": [{"name": "togekiss", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "469": [{"name": "yanmega", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "470": [{"name": "leafeon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "471": [{"name": "glaceon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "472": [{"name": "gliscor", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "473": [{"name": "mamoswine", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "474": [{"name": "porygon-z", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "475": [{"name": "gallade", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "476": [{"name": "probopass", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "477": [{"name": "dusknoir", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "478": [{"name": "froslass", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "479": [{"name": "rotom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "480": [{"name": "uxie", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "481": [{"name": "mesprit", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "482": [{"name": "azelf", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "483": [{"name": "dialga", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "484": [{"name": "palkia", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "485": [{"name": "heatran", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "486": [{"name": "regigigas", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "487": [{"name": "giratina", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "488": [{"name": "cresselia", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "489": [{"name": "phione", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "490": [{"name": "manaphy", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "491": [{"name": "darkrai", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "492": [{"name": "shaymin", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "493": [{"name": "arceus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "494": [{"name": "victini", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "495": [{"name": "snivy", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "496": [{"name": "servine", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "497": [{"name": "serperior", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "498": [{"name": "tepig", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "499": [{"name": "pignite", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "500": [{"name": "emboar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "501": [{"name": "oshawott", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "502": [{"name": "dewott", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "503": [{"name": "samurott", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "504": [{"name": "patrat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "505": [{"name": "watchog", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "506": [{"name": "lillipup", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "507": [{"name": "herdier", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "508": [{"name": "stoutland", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "509": [{"name": "purrloin", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "510": [{"name": "liepard", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "511": [{"name": "pansage", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "512": [{"name": "simisage", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "513": [{"name": "pansear", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "514": [{"name": "simisear", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "515": [{"name": "panpour", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "516": [{"name": "simipour", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "517": [{"name": "munna", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "518": [{"name": "musharna", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "519": [{"name": "pidove", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "520": [{"name": "tranquill", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "521": [{"name": "unfezant", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "522": [{"name": "blitzle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "523": [{"name": "zebstrika", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "524": [{"name": "roggenrola", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "525": [{"name": "boldore", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "526": [{"name": "gigalith", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "527": [{"name": "woobat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "528": [{"name": "swoobat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "529": [{"name": "drilbur", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "530": [{"name": "excadrill", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "531": [{"name": "audino", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "532": [{"name": "timburr", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "533": [{"name": "gurdurr", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "534": [{"name": "conkeldurr", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "535": [{"name": "tympole", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "536": [{"name": "palpitoad", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "537": [{"name": "seismitoad", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "538": [{"name": "throh", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "539": [{"name": "sawk", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "540": [{"name": "sewaddle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "541": [{"name": "swadloon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "542": [{"name": "leavanny", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "543": [{"name": "venipede", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "544": [{"name": "whirlipede", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "545": [{"name": "scolipede", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "546": [{"name": "cottonee", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "547": [{"name": "whimsicott", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "548": [{"name": "petilil", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "549": [{"name": "lilligant", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "550": [{"name": "basculin", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "551": [{"name": "sandile", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "552": [{"name": "krokorok", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "553": [{"name": "krookodile", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "554": [{"name": "darumaka", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "555": [{"name": "darmanitan", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "556": [{"name": "maractus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "557": [{"name": "dwebble", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "558": [{"name": "crustle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "559": [{"name": "scraggy", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "560": [{"name": "scrafty", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "561": [{"name": "sigilyph", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "562": [{"name": "yamask", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "563": [{"name": "cofagrigus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "564": [{"name": "tirtouga", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "565": [{"name": "carracosta", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "566": [{"name": "archen", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "567": [{"name": "archeops", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "568": [{"name": "trubbish", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "569": [{"name": "garbodor", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "570": [{"name": "zorua", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "571": [{"name": "zoroark", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "572": [{"name": "minccino", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "573": [{"name": "cinccino", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "574": [{"name": "gothita", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "575": [{"name": "gothorita", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "576": [{"name": "gothitelle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "577": [{"name": "solosis", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "578": [{"name": "duosion", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "579": [{"name": "reuniclus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "580": [{"name": "ducklett", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "581": [{"name": "swanna", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "582": [{"name": "vanillite", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "583": [{"name": "vanillish", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "584": [{"name": "vanilluxe", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "585": [{"name": "deerling", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "586": [{"name": "sawsbuck", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "587": [{"name": "emolga", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "588": [{"name": "karrablast", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "589": [{"name": "escavalier", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "590": [{"name": "foongus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "591": [{"name": "amoonguss", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "592": [{"name": "frillish", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "593": [{"name": "jellicent", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "594": [{"name": "alomomola", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "595": [{"name": "joltik", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "596": [{"name": "galvantula", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "597": [{"name": "ferroseed", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "598": [{"name": "ferrothorn", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "599": [{"name": "klink", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "600": [{"name": "klang", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "601": [{"name": "klinklang", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "602": [{"name": "tynamo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "603": [{"name": "eelektrik", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "604": [{"name": "eelektross", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "605": [{"name": "elgyem", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "606": [{"name": "beheeyem", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "607": [{"name": "litwick", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "608": [{"name": "lampent", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "609": [{"name": "chandelure", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "610": [{"name": "axew", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "611": [{"name": "fraxure", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "612": [{"name": "haxorus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "613": [{"name": "cubchoo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "614": [{"name": "beartic", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "615": [{"name": "cryogonal", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "616": [{"name": "shelmet", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "617": [{"name": "accelgor", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "618": [{"name": "stunfisk", "alola": false, "galar": true,
		"hisuian": false,
		"gender": false}],
        "619": [{"name": "mienfoo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "620": [{"name": "mienshao", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "621": [{"name": "druddigon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "622": [{"name": "golett", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "623": [{"name": "golurk", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "624": [{"name": "pawniard", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "625": [{"name": "bisharp", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "626": [{"name": "bouffalant", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "627": [{"name": "rufflet", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "628": [{"name": "braviary", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "629": [{"name": "vullaby", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "630": [{"name": "mandibuzz", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "631": [{"name": "heatmor", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "632": [{"name": "durant", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "633": [{"name": "deino", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "634": [{"name": "zweilous", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "635": [{"name": "hydreigon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "636": [{"name": "larvesta", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "637": [{"name": "volcarona", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "638": [{"name": "cobalion", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "639": [{"name": "terrakion", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "640": [{"name": "virizion", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "641": [{"name": "tornadus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "642": [{"name": "thundurus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "643": [{"name": "reshiram", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "644": [{"name": "zekrom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "645": [{"name": "landorus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "646": [{"name": "kyurem", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "647": [{"name": "keldeo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "648": [{"name": "meloetta", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "649": [{"name": "genesect", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "650": [{"name": "chespin", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "651": [{"name": "quilladin", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "652": [{"name": "chesnaught", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "653": [{"name": "fennekin", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "654": [{"name": "braixen", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "655": [{"name": "delphox", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "656": [{"name": "froakie", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "657": [{"name": "frogadier", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "658": [{"name": "greninja", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "659": [{"name": "bunnelby", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "660": [{"name": "diggersby", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "661": [{"name": "fletchling", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "662": [{"name": "fletchinder", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "663": [{"name": "talonflame", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "664": [{"name": "scatterbug", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "665": [{"name": "spewpa", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "666": [{"name": "vivillon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "667": [{"name": "litleo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "668": [{"name": "pyroar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "669": [{"name": "flabebe", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "670": [{"name": "floette", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "671": [{"name": "florges", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "672": [{"name": "skiddo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "673": [{"name": "gogoat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "674": [{"name": "pancham", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "675": [{"name": "pangoro", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "676": [{"name": "furfrou", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "677": [{"name": "espurr", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "678": [{"name": "meowstic", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "679": [{"name": "honedge", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "680": [{"name": "doublade", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "681": [{"name": "aegislash", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "682": [{"name": "spritzee", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "683": [{"name": "aromatisse", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "684": [{"name": "swirlix", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "685": [{"name": "slurpuff", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "686": [{"name": "inkay", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "687": [{"name": "malamar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "688": [{"name": "binacle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "689": [{"name": "barbaracle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "690": [{"name": "skrelp", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "691": [{"name": "dragalge", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "692": [{"name": "clauncher", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "693": [{"name": "clawitzer", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "694": [{"name": "helioptile", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "695": [{"name": "heliolisk", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "696": [{"name": "tyrunt", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "697": [{"name": "tyrantrum", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "698": [{"name": "amaura", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "699": [{"name": "aurorus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "700": [{"name": "sylveon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "701": [{"name": "hawlucha", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "702": [{"name": "dedenne", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "703": [{"name": "carbink", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "704": [{"name": "goomy", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "705": [{"name": "sliggoo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "706": [{"name": "goodra", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "707": [{"name": "klefki", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "708": [{"name": "phantump", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "709": [{"name": "trevenant", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "710": [{"name": "pumpkaboo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "711": [{"name": "gourgeist", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "712": [{"name": "bergmite", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "713": [{"name": "avalugg", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "714": [{"name": "noibat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "715": [{"name": "noivern", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "716": [{"name": "xerneas", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "717": [{"name": "yveltal", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "718": [{"name": "zygarde", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "719": [{"name": "diancie", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "720": [{"name": "hoopa", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "721": [{"name": "volcanion", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "722": [{"name": "rowlet", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "723": [{"name": "dartrix", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "724": [{"name": "decidueye", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "725": [{"name": "litten", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "726": [{"name": "torracat", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "727": [{"name": "incineroar", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "728": [{"name": "popplio", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "729": [{"name": "brionne", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "730": [{"name": "primarina", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "731": [{"name": "pikipek", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "732": [{"name": "trumbeak", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "733": [{"name": "toucannon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "734": [{"name": "yungoos", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "735": [{"name": "gumshoos", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "736": [{"name": "grubbin", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "737": [{"name": "charjabug", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "738": [{"name": "vikavolt", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "739": [{"name": "crabrawler", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "740": [{"name": "crabominable", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "741": [{"name": "oricorio", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "742": [{"name": "cutiefly", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "743": [{"name": "ribombee", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "744": [{"name": "rockruff", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "745": [{"name": "lycanroc", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "746": [{"name": "wishiwashi", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "747": [{"name": "mareanie", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "748": [{"name": "toxapex", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "749": [{"name": "mudbray", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "750": [{"name": "mudsdale", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "751": [{"name": "dewpider", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "752": [{"name": "araquanid", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "753": [{"name": "fomantis", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "754": [{"name": "lurantis", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "755": [{"name": "morelull", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "756": [{"name": "shiinotic", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "757": [{"name": "salandit", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "758": [{"name": "salazzle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "759": [{"name": "stufful", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "760": [{"name": "bewear", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "761": [{"name": "bounsweet", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "762": [{"name": "steenee", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "763": [{"name": "tsareena", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "764": [{"name": "comfey", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "765": [{"name": "oranguru", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "766": [{"name": "passimian", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "767": [{"name": "wimpod", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "768": [{"name": "golisopod", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "769": [{"name": "sandygast", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "770": [{"name": "palossand", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "771": [{"name": "pyukumuku", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "772": [{"name": "type-null", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "773": [{"name": "silvally", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "774": [{"name": "minior", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "775": [{"name": "komala", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "776": [{"name": "turtonator", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "777": [{"name": "togedemaru", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "778": [{"name": "mimikyu", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "779": [{"name": "bruxish", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "780": [{"name": "drampa", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "781": [{"name": "dhelmise", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "782": [{"name": "jangmo-o", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "783": [{"name": "hakamo-o", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "784": [{"name": "kommo-o", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "785": [{"name": "tapu-koko", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "786": [{"name": "tapu-lele", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "787": [{"name": "tapu-bulu", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "788": [{"name": "tapu-fini", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "789": [{"name": "cosmog", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "790": [{"name": "cosmoem", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "791": [{"name": "solgaleo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "792": [{"name": "lunala", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "793": [{"name": "nihilego", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "794": [{"name": "buzzwole", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "795": [{"name": "pheromosa", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "796": [{"name": "xurkitree", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "797": [{"name": "celesteela", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "798": [{"name": "kartana", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "799": [{"name": "guzzlord", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "800": [{"name": "necrozma", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "801": [{"name": "magearna", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "802": [{"name": "marshadow", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "803": [{"name": "poipole", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "804": [{"name": "naganadel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "805": [{"name": "stakataka", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "806": [{"name": "blacephalon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "807": [{"name": "zeraora", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "808": [{"name": "meltan", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "809": [{"name": "melmetal", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "810": [{"name": "grookey", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "811": [{"name": "thwackey", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "812": [{"name": "rillaboom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "813": [{"name": "scorbunny", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "814": [{"name": "raboot", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "815": [{"name": "cinderace", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "816": [{"name": "sobble", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "817": [{"name": "drizzile", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "818": [{"name": "inteleon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "819": [{"name": "skwovet", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "820": [{"name": "greedent", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "821": [{"name": "rookidee", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "822": [{"name": "corvisquire", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "823": [{"name": "corviknight", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "824": [{"name": "blipbug", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "825": [{"name": "dottler", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "826": [{"name": "orbeetle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "827": [{"name": "nickit", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "828": [{"name": "thievul", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "829": [{"name": "gossifleur", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "830": [{"name": "eldegoss", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "831": [{"name": "wooloo", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "832": [{"name": "dubwool", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "833": [{"name": "chewtle", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "834": [{"name": "drednaw", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "835": [{"name": "yamper", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "836": [{"name": "boltund", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "837": [{"name": "rolycoly", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "838": [{"name": "carkol", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "839": [{"name": "coalossal", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "840": [{"name": "applin", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "841": [{"name": "flapple", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "842": [{"name": "appletun", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "843": [{"name": "silicobra", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "844": [{"name": "sandaconda", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "845": [{"name": "cramorant", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "846": [{"name": "arrokuda", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "847": [{"name": "barraskewda", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "848": [{"name": "toxel", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "849": [{"name": "toxtricity", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "850": [{"name": "sizzlipede", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "851": [{"name": "centiskorch", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "852": [{"name": "clobbopus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "853": [{"name": "grapploct", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "854": [{"name": "sinistea", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "855": [{"name": "polteageist", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "856": [{"name": "hatenna", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "857": [{"name": "hattrem", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "858": [{"name": "hatterene", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "859": [{"name": "impidimp", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "860": [{"name": "morgrem", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "861": [{"name": "grimmsnarl", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "862": [{"name": "obstagoon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "863": [{"name": "perrserker", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "864": [{"name": "cursola", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "865": [{"name": "sirfetchd", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "866": [{"name": "mr-rime", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "867": [{"name": "runerigus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "868": [{"name": "milcery", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "869": [{"name": "alcremie", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "870": [{"name": "falinks", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "871": [{"name": "pincurchin", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "872": [{"name": "snom", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "873": [{"name": "frosmoth", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "874": [{"name": "stonjourner", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "875": [{"name": "eiscue", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "876": [{"name": "indeedee", "alola": false, "galar": false,
		"hisuian": false,
		"gender": true}],
        "877": [{"name": "morpeko", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "878": [{"name": "cufant", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "879": [{"name": "copperajah", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "880": [{"name": "dracozolt", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "881": [{"name": "arctozolt", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "882": [{"name": "dracovish", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "883": [{"name": "arctovish", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "884": [{"name": "duraludon", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "885": [{"name": "dreepy", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "886": [{"name": "drakloak", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "887": [{"name": "dragapult", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "888": [{"name": "zacian", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "889": [{"name": "zamazenta", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}],
        "890": [{"name": "eternatus", "alola": false, "galar": false,
		"hisuian": false,
		"gender": false}]
    }';

?>